### ISSUE TITLE
Web Push notifications

### ISSUE THREAD

**Issue by Hello1024** [meteyou/mainsail#1793]
### Requested feature:

Use the Web Push API to give notifications when prints are done/errors.

### Solves the following problem:

More general purpose than telegram/mqtt integration.  Works across iOS/Android/Windows/Mac/Linux.  

Probably requires work in both mainsail and moonraker.

**Comment by meteyou** [comment]
This is not really possible, because mainsail itself is only running in the browser and has no part on the host. But the bigger issue is, that you need an SSL encrypted connection to be allowed to create push notifications... So as long as there is no easy way to have SSL certs for everyone in there local network, this is not really possible.
