### ISSUE TITLE
Temperature presets appearing after filling in the temperature manually.

### ISSUE THREAD

**Issue by MarcPot** [meteyou/mainsail#189]
When manually filling in a temperature, the preset list is acting unexpected.

First when clicking the temp it appears (expected behaviour).
![image](https://user-images.githubusercontent.com/7275765/106896368-c26ce500-66f1-11eb-8031-7b39d6555e0b.png)
Then when typing in the temperature it disappears (expected behaviour).
![image](https://user-images.githubusercontent.com/7275765/106896766-4b841c00-66f2-11eb-8dea-8771ce459e9a.png)
But then when pressing enter because you filled it in, it appears again (unexpected behaviour).
![image](https://user-images.githubusercontent.com/7275765/106896854-6a82ae00-66f2-11eb-92d0-636446a2b12e.png)

The reason why it's annoying is because the preset bar overlaps the other temperature textboxes, so I first have to click somewhere random before being able the continue.

**Comment by DruckiMcDruck** [comment]
I also have this issue, i'm running Mainsail v1.1.0.

**Comment by meteyou** [comment]
thats the way, how a combobox work. its a input field and a select/dropdown box in one.

**Comment by MarcPot** [comment]
Yes but my expectation would be that the dropdown would disappear after pressing enter.

If this is the standard behavior I’d prefer a simple input field. But I guess the dropdown box is useful for mobile users?

**Comment by meteyou** [comment]
its the same if you set a value or you will change a value. if your printer is set to 200° and you will set it higher or lower with a click/touch in the field, you would need this values again. i cannot separate these 2 situations

**Comment by MarcPot** [comment]
To bad. Thanks anyways!

**Comment by meteyou** [comment]
i will check it again, but at the moment i don't know a way out...

**Comment by intelinc** [comment]
This is a perpetual issue for me on desktop and mobile. The nonstandard behavior is mainly that hitting enter should set the temp and remove the selections. It does the former, but not the latter, which requires an additional click outside of the temp combobox to fully "fix" the temp selected. Maybe this works well for dropdown selections, but I tend to work across a lot of filament types, so I just type the temp in. 

An additional problem with the dropdown remaining is that the extruder temp dropdown is almost visually identical to bed temp. 

inactive temp menu:
![Image on 2022-05-16 12 31 15 PM](https://user-images.githubusercontent.com/9275860/168669337-156acadf-1e32-4a93-80c1-e9bd16fb5cb8.jpg)

extruder temp dropdown superimposed over bed temp:
![Image on 2022-05-16 12 45 09 PM](https://user-images.githubusercontent.com/9275860/168670355-417d2765-0924-4a2c-8a8d-ee4788885998.jpg)


At a glance and on mobile, these are visually equivalent, so I am constantly typing in the extruder temp, pressing "enter" and then clicking the 0℃ dropdown when I mean to set the bed temp. So instead of setting the bed temp, I inadvertently set the extruder back to zero. Constantly. It's just muscle memory from a few years of running Fluidd (which does clear the dropdown on enter) before switching to Mainsail.

**Comment by th33xitus** [comment]
@intelinc 
In the current beta release, we got rid of the combined dropdown. now a dropdown with presets will only open, if you click on a button with the caret down symbol. the temperature input field will not toggle a dropdown.
so once v2.2.0 is released you will not have this issue anymore. or you update now to the current v.2.2.0-beta3 and get rid of that issue immediately :P the choice is yours.

**Comment by intelinc** [comment]
@th33xitus thanks for letting me know. Looking forward to trying this out!
