### ISSUE TITLE
Unclear use of custom G-Code in "Presets"

### ISSUE THREAD

**Issue by dewi-ny-je** [meteyou/mainsail#196]
The website and the UI show how gcode can be added to temperature presets.

It is not clear the sequence: will the temperature be set and then the gcode executed, or gcode first?

I have a macro to wait for a PWM value of the bed heater, but I need it to run after the temperature has been set.
Of course I could add the command for the temperature to the gcode section, but I think that the interface should make clear how the gcode field works.

**Comment by lixxbox** [comment]
Create a preset, with temperatures and a simple gcode and run it. The console will document the order in which the commands are executed.

**Comment by meteyou** [comment]
you can test it or you can see it in the code itself. pls ask the next time on discord and dont open a issue ticket for questions like this.

here is the code block of the presets: https://github.com/meteyou/mainsail/blob/master/src/components/panels/ToolsPanel.vue#L311

at first all heaters + fans and then the gcode. i add a delay between heaters and gcode to seperate it in the console log. sometimes the console mixed it up because it will be execute in the same second.

**Comment by dewi-ny-je** [comment]
@meteyou indeed I should have not marked it as bug, but before a request for support, this ticket was meant to request support in the documentation.

I can do it myself if you tell me on which page you would like to have it.

My point is that users should not be expected to discover it themselves... Either it should be obvious from the label in the interface, or it should be mentioned in the docs.

**Comment by meteyou** [comment]
ok. then i misunderstood. i have already forwarded it to @lixxbox. he mainly create the docs. i think it would be here right: https://docs.mainsail.xyz/quicktips/presets
