### ISSUE TITLE
Saving mesh in HEIGHTMAP menu results in "Klipper Not Ready HEIGHTMAP Disabled"

### ISSUE THREAD

**Issue by bill-orange** [meteyou/mainsail#334]
**Describe the bug:

When attempting to save a Mesh in the HEIGHTMAP menu an error message is issued "Klipper Not Ready HEIGHTMAP Disabled".  This leave the user unsure if the Mesh was saved or not.  Saving the Mesh in the Dashboard Menu works fine.

**Expected behavior:

Mesh is saved without (likely false) error.  Immediately after  executing a successful save, this message should be suppressed.

**Screenshots: N/A

**Logfiles:
Attached as noted:

[Downloads.zip](https://github.com/meteyou/mainsail/files/7024844/Downloads.zip)

**Comment by meteyou** [comment]
this is just the warning, during the klipper restart

**Comment by dnewell73** [comment]
Why doesn't the mesh show up as saved?

**Comment by jjl40** [comment]
This is confusing. Are you saying just ignore this error message?

**Comment by meteyou** [comment]
@jjl40 Mainsail is just a GUI and display the current state from Klipper. SAVE_CONFIG is a Klipper command, which restart Klipper. While restarting, Klipper is a short time not available and during this time, Mainsail cannot display anything from Klipper, because it is not available. so what should i display? just nothing? Or should i display the correct state "Klipper not ready"? because in this situation, i dont know if you just open this page or will maybe Klipper will never start, because of an issue in your config?

**Comment by jjl40** [comment]
Stefan

Thank you for the explanation.
This is my first project using Mainsail, on a new control board. So I’m learning a lot.
Your explanation is very clear and I appreciate your taking the time to clear up my confusion.

Cheers

John Lytle



On Aug 29, 2024, at 5:34 PM, Stefan Dej ***@***.***> wrote:

﻿

@jjl40<https://github.com/jjl40> Mainsail is just a GUI and display the current state from Klipper. SAVE_CONFIG is a Klipper command, which restart Klipper. While restarting, Klipper is a short time not available and during this time, Mainsail cannot display anything from Klipper, because it is not available. so what should i display? just nothing? Or should i display the correct state "Klipper not ready"? because in this situation, i dont know if you just open this page or will maybe Klipper will never start, because of an issue in your config?
