### ISSUE TITLE
Thumbnail Preview not showing

### ISSUE THREAD

**Issue by atharvbadkas** [meteyou/mainsail#347]
**Describe the bug:**\
Mainsail dont load thumbnail, even when print starts, on main page it shows blank space.

**Expected behavior:**\
Should have shown thumbnail, I also have updated the moonraker dependencies using SSH.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/57062058/131999929-a85f0aaa-9b43-4020-850d-f6049418935d.png)

**Logfiles:**\
[moonraker.log](https://github.com/meteyou/mainsail/files/7105597/moonraker.log)
[klippy.log](https://github.com/meteyou/mainsail/files/7105599/klippy.log)

I have recently migrated from Marlin and have limited experience with linux systems and R pi stuff.
I'm using cura slicer and cura2moonraker plugin.
thumbnail gets created in .thumbs folder but it doesnt apply.

**Comment by meteyou** [comment]
pls upload one of the gcode files

**Comment by atharvbadkas** [comment]
Hi,
I tried without inserting " , " in name but didnt work.

Heres GCODE ( purposely renamed to TXT to upload here)
[9_Q016_A.txt](https://github.com/meteyou/mainsail/files/7111216/9_Q016_A.txt)

**Comment by meteyou** [comment]
thx for the gcode. i think i found your issue. the problem is, that your gcode have only the big thumbnail in it. the next issue is, that you have a thumbnail in the gcode. if you use the cura moonraker plugin, you should upload the UFP file and not the gcode. this file is like a zip file with the files in it. is it possible, that you use the postprocessing to add the thumbnails in your gcode file? if you use it, pls add a second thumbnail with 32x32px.

**Comment by atharvbadkas** [comment]
Thanks, adding second thumbnail size made it work!
