### ISSUE TITLE
Cant run resonance compensation

### ISSUE THREAD

**Issue by TjardF** [meteyou/mainsail#354]
**Describe the bug:**\
I finally got everything configured on my completely upgraded Mega S.
I started resonance Compensation, sensor works, it runs fine until it hit 13Hz. At this Point the Printer (including Mainsail UI) freezes for about one minute.
Next it reports 100% Host usage and a Timeout.
I'm currently only running a Pi Zero W, isn't it powerful enough for that test?

**Expected behavior:**\
A Solution, maybe I did a mistake or somebody else also tried Pi Zero and its just not powerful enough, would be sad, but at least it is a possible solution

**Screenshots:**\

**Logfiles:**\
[klippy-3.log](https://github.com/meteyou/mainsail/files/7149701/klippy-3.log)
[moonraker-2.log](https://github.com/meteyou/mainsail/files/7149702/moonraker-2.log)

**Comment by meteyou** [comment]
mainsail is just a web gui and it is only executed in your browser. this issue is just a klipper performance issue.

the main problem is the single core cpu if the pi zero. it cannot messure the frequence, handle the background os stuff and coordinate klipper at the same time.

yes klipper works on a pi zero, but you cannot use everything, because of the single core cpu.
